# Generated by Django 6.1.1 on 2026-09-08 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Engagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(default='deal', max_length=20)),
                ('counterparty_id', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=200)),
                ('value_minor', models.BigIntegerField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, default='', max_length=8)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateTimeField()),
                ('direction', models.CharField(max_length=4)),
                ('amount_minor', models.BigIntegerField()),
                ('currency', models.CharField(default='CNY', max_length=8)),
                ('label', models.CharField(max_length=200)),
                ('status', models.CharField(default='expected', max_length=10)),
                ('engagement_id', models.IntegerField(blank=True, null=True)),
                ('person_id', models.IntegerField(blank=True, null=True)),
                ('occasion_tag', models.CharField(blank=True, default='', max_length=40)),
            ],
            options={
                'verbose_name_plural': 'money',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateTimeField()),
                ('text', models.TextField(blank=True, default='')),
                ('person_id', models.IntegerField(blank=True, null=True)),
                ('engagement_id', models.IntegerField(blank=True, null=True)),
                ('tag', models.CharField(blank=True, default='', max_length=40)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Occasion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=120)),
                ('date', models.DateTimeField()),
                ('tag', models.CharField(max_length=40)),
                ('country', models.CharField(blank=True, default='', max_length=20)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('company', models.CharField(blank=True, default='', max_length=200)),
                ('wa_number', models.CharField(blank=True, default='', max_length=40)),
                ('wechat_id', models.CharField(blank=True, default='', max_length=100)),
                ('preferred_channel', models.CharField(default='wa', max_length=10)),
                ('met_where', models.CharField(blank=True, default='', max_length=200)),
                ('met_when', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('occasion_tags', models.CharField(blank=True, default='', max_length=300)),
                ('ping_date', models.DateTimeField(blank=True, null=True)),
                ('ping_note', models.CharField(blank=True, default='', max_length=300)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Touch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('person_id', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('one_line', models.CharField(blank=True, default='', max_length=300)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
