# Generated by Django 6.1.1 on 2026-09-11 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('label', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(db_index=True, max_length=36)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateTimeField()),
                ('direction', models.CharField(max_length=4)),
                ('amount_minor', models.BigIntegerField()),
                ('currency', models.CharField(default='CNY', max_length=8)),
                ('label', models.CharField(max_length=200)),
                ('status', models.CharField(default='expected', max_length=10)),
                ('engagement_id', models.CharField(blank=True, default='', max_length=36)),
                ('person_id', models.CharField(blank=True, default='', max_length=36)),
                ('occasion_tag', models.CharField(blank=True, default='', max_length=40)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'money',
            },
        ),
        migrations.CreateModel(
            name='Occasion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(db_index=True, max_length=36)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=120)),
                ('date', models.DateTimeField()),
                ('tag', models.CharField(max_length=40)),
                ('country', models.CharField(blank=True, default='', max_length=20)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Engagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(db_index=True, max_length=36)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(default='deal', max_length=20)),
                ('counterparty_id', models.CharField(blank=True, default='', max_length=36)),
                ('status', models.CharField(blank=True, default='', max_length=200)),
                ('value_minor', models.BigIntegerField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, default='', max_length=8)),
                ('notes', models.TextField(blank=True, default='')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('owner', 'client_id'), name='engagement_unique_owner_row')],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(db_index=True, max_length=36)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateTimeField()),
                ('text', models.TextField(blank=True, default='')),
                ('person_id', models.CharField(blank=True, default='', max_length=36)),
                ('engagement_id', models.CharField(blank=True, default='', max_length=36)),
                ('tag', models.CharField(blank=True, default='', max_length=40)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('owner', 'client_id'), name='note_unique_owner_row')],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(db_index=True, max_length=36)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('company', models.CharField(blank=True, default='', max_length=200)),
                ('wa_number', models.CharField(blank=True, default='', max_length=40)),
                ('wechat_id', models.CharField(blank=True, default='', max_length=100)),
                ('preferred_channel', models.CharField(default='wa', max_length=10)),
                ('met_where', models.CharField(blank=True, default='', max_length=200)),
                ('met_when', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('occasion_tags', models.CharField(blank=True, default='', max_length=300)),
                ('ping_date', models.DateTimeField(blank=True, null=True)),
                ('ping_note', models.CharField(blank=True, default='', max_length=300)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('owner', 'client_id'), name='person_unique_owner_row')],
            },
        ),
        migrations.CreateModel(
            name='Touch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(db_index=True, max_length=36)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('person_id', models.CharField(max_length=36)),
                ('date', models.DateTimeField()),
                ('one_line', models.CharField(blank=True, default='', max_length=300)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('owner', 'client_id'), name='touch_unique_owner_row')],
            },
        ),
    ]
