# Generated by Django 6.1.1 on 2026-09-12 03:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(db_index=True, max_length=36)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('person_id', models.CharField(blank=True, default='', max_length=36)),
                ('engagement_id', models.CharField(blank=True, default='', max_length=36)),
                ('title', models.CharField(max_length=200)),
                ('starts_at', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(default=60)),
                ('location', models.CharField(blank=True, default='', max_length=200)),
                ('notes', models.TextField(blank=True, default='')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('owner', 'client_id'), name='meeting_unique_owner_row')],
            },
        ),
    ]
