# Generated by Django 6.1.1 on 2026-09-17 03:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_occasion_greeting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OccasionTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(db_index=True, max_length=36)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('slug', models.CharField(max_length=40)),
                ('label', models.CharField(max_length=120)),
                ('hint', models.CharField(blank=True, default='', max_length=120)),
                ('greeting', models.TextField(blank=True, default='')),
                ('sort_order', models.IntegerField(default=0)),
                ('built_in', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'label'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('owner', 'client_id'), name='occasiontag_unique_owner_row')],
            },
        ),
    ]
