"""
Django settings for crm project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
#
# ⚠ From the environment, because this repository is public. Django signs
# sessions, CSRF tokens and password-reset links with this; a published key
# means anyone can forge them. Set DJANGO_SECRET_KEY on the VPS alongside
# SYNC_TOKEN. The fallback is for local development only and is marked
# insecure so Django's own deployment check flags it.
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY", "django-insecure-local-development-only")

# SECURITY WARNING: don't run with debug turned on in production!
#
# ⚠ Defaults to OFF. It used to default to True, which meant forgetting one
# environment variable served a full stack trace — settings, local variables,
# the SQL around the error — to anyone who could trigger a 500 on a public IP.
# The safe value is the one you get by forgetting.
DEBUG = os.environ.get("DJANGO_DEBUG", "") == "1"

# ⚠ Was ["*"]. Behind Caddy that is survivable, but it also means the app
# answers to any Host header, which is what makes cache-poisoning and
# password-reset-link forgery work. Set DJANGO_ALLOWED_HOSTS=crm.example.com.
ALLOWED_HOSTS = [
    h.strip()
    for h in os.environ.get("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")
    if h.strip()
]

# Caddy terminates TLS and proxies plain HTTP to gunicorn, so without this
# Django believes every request is insecure and the redirect below loops.
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    CSRF_TRUSTED_ORIGINS = [f"https://{h}" for h in ALLOWED_HOSTS]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'core.middleware.BearerTokenMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'crm.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'crm.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}

# ⚠ One bearer token. THE TOKEN IS THE ACCOUNT — for one person with two
# devices that is the correct design, and it is not optional: an open API on a
# public IP is found by scanners within hours, and the contact list and the
# cashflow are both in there.
_DEV_TOKEN = "dev-token-change-me"
SYNC_TOKEN = os.environ.get("SYNC_TOKEN", _DEV_TOKEN)

# ⚠⚠ REFUSE TO BOOT rather than serve with the development token.
#
# This file is in a PUBLIC repository, so "dev-token-change-me" is a password
# the entire internet can read. Deploying without setting SYNC_TOKEN would have
# worked perfectly — sync would sync, nothing would look wrong — while leaving
# every contact and every money row readable and writable by anyone who found
# the host. That is this project's defining failure mode: armed and dead looks
# exactly like fine. So it fails loudly, at startup, before it can serve once.
if not DEBUG and SYNC_TOKEN == _DEV_TOKEN:
    from django.core.exceptions import ImproperlyConfigured

    raise ImproperlyConfigured(
        "SYNC_TOKEN is still the public development default. Set it to a real "
        "secret, e.g. SYNC_TOKEN=$(python3 -c 'import secrets;"
        "print(secrets.token_urlsafe(32))'), and put the same value in the "
        "app's lib/domain/config.dart."
    )

# SQLite: backups are `scp` on one file. No scale argument at one user.
USE_TZ = True
