"""
Django settings for crm project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
#
# ⚠ From the environment, because this repository is public. Django signs
# sessions, CSRF tokens and password-reset links with this; a published key
# means anyone can forge them. Set DJANGO_SECRET_KEY on the VPS alongside
# SYNC_TOKEN. The fallback is for local development only and is marked
# insecure so Django's own deployment check flags it.
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY", "django-insecure-local-development-only")

# SECURITY WARNING: don't run with debug turned on in production!
#
# ⚠ Defaults to OFF. It used to default to True, which meant forgetting one
# environment variable served a full stack trace — settings, local variables,
# the SQL around the error — to anyone who could trigger a 500 on a public IP.
# The safe value is the one you get by forgetting.
DEBUG = os.environ.get("DJANGO_DEBUG", "") == "1"

# ⚠ Was ["*"]. Behind Caddy that is survivable, but it also means the app
# answers to any Host header, which is what makes cache-poisoning and
# password-reset-link forgery work. Set DJANGO_ALLOWED_HOSTS=crm.example.com.
ALLOWED_HOSTS = [
    h.strip()
    for h in os.environ.get("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")
    if h.strip()
]

# Caddy terminates TLS and proxies plain HTTP to gunicorn, so without this
# Django believes every request is insecure and the redirect below loops.
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    CSRF_TRUSTED_ORIGINS = [f"https://{h}" for h in ALLOWED_HOSTS]


# Application definition

# ⚠ django.contrib.admin is deliberately absent. It is a browser surface that
# a bearer token cannot guard, at a URL every scanner tries, and the clients
# never needed it — the Dart seedIfEmpty() builds the occasion calendar on each
# device. Accounts replaced it as the way in.
INSTALLED_APPS = [
    'django.contrib.auth',          # the User model and password hashing
    'django.contrib.contenttypes',  # auth depends on it
    'core',
]

# ⚠ This is a JSON API for native clients. With the admin gone there is no
# browser surface at all, so the browser-only middleware is removed rather than
# left running: sessions, CSRF, messages and clickjacking all exist to defend a
# cookie that no longer exists.
#
# ⚠ AuthenticationMiddleware in particular had to go. It ran AFTER ours and
# replaced the request.user we had just set with AnonymousUser, so an
# authenticated request reported no user. Found by a test.
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.common.CommonMiddleware',
    'core.middleware.BearerTokenMiddleware',
]

ROOT_URLCONF = 'crm.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'crm.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}

# ⚠ Tokens now belong to ACCOUNTS, not to the deployment — see core/auth.py.
# There is no shared secret in this file any more.
#
# REGISTRATION IS CLOSED BY DEFAULT, and this is the important part. The models
# carry NO owner column: every row belongs to the deployment, not to a user. So
# a second account would not get its own data, it would get YOURS. Registration
# therefore requires BOTH this secret AND that no account exists yet.
#
# Leaving it unset disables registration entirely, which is the correct state
# for every moment after you have made your one account. Without it, a fresh
# public server is a race between you and whoever scans it first.
REGISTRATION_SECRET = os.environ.get("REGISTRATION_SECRET", "")

# SQLite: backups are `scp` on one file. No scale argument at one user.
USE_TZ = True
