"""Mirrors the Flutter/drift schema. ⚠ Every table carries updated_at and
deleted_at. Soft deletes only — a hard-deleted row leaves nothing to tell the
other device it is gone, so it syncs straight back."""
from django.db import models


class SyncedModel(models.Model):
    # ⚠ WHO OWNS THIS ROW. Added when the server became multi-user. Every query
    # in core/sync.py filters on it; a row nobody owns is returned to nobody,
    # which is the fail-closed direction.
    owner = models.ForeignKey(
        "auth.User", on_delete=models.CASCADE, null=True, related_name="+"
    )

    # ⚠ UUID text id, generated by whichever client created the row — NOT
    # autoincrement. Two devices with independent integer sequences produce
    # different rows sharing an id, and last-write-wins then merges them and
    # destroys one. The server never mints an id.
    #
    # ⚠ IT IS NO LONGER THE PRIMARY KEY. It is unique PER OWNER, and that is
    # not a refinement — it is required. Seeded occasion ids are UUID v5 of
    # name+date (see seededId in the Dart), deliberately identical on every
    # device so one user's Mac and phone collapse to one row. Across users they
    # are identical too, so a globally unique id would make the second user's
    # entire festival calendar collide with the first's and vanish. Scoping
    # uniqueness to the owner keeps the collapse within an account and makes it
    # impossible between accounts — enforced by the database, not by a check
    # someone can forget.
    #
    # ⚠ Named client_id, not id, because Django reserves `id` for the primary
    # key. The WIRE PROTOCOL IS UNCHANGED: core/sync.py still reads and writes
    # it as "id", which is what the Dart client has always sent.
    client_id = models.CharField(max_length=36, db_index=True)

    # ⚠ THE SERVER STAMPS updated_at. Clients NEVER set it. If the phone and
    # the Mac disagree by minutes, client-set timestamps make last-write-wins
    # pick the wrong winner and an edit vanishes silently. One clock.
    updated_at = models.DateTimeField(auto_now=True, db_index=True)
    deleted_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        abstract = True
        constraints = [
            models.UniqueConstraint(
                fields=["owner", "client_id"],
                name="%(class)s_unique_owner_row",
            )
        ]


class Person(SyncedModel):
    name = models.CharField(max_length=200)
    company = models.CharField(max_length=200, blank=True, default="")
    wa_number = models.CharField(max_length=40, blank=True, default="")
    wechat_id = models.CharField(max_length=100, blank=True, default="")
    preferred_channel = models.CharField(max_length=10, default="wa")
    met_where = models.CharField(max_length=200, blank=True, default="")
    met_when = models.DateTimeField(null=True, blank=True)
    notes = models.TextField(blank=True, default="")
    # Comma-joined tag list, same encoding as the client.
    occasion_tags = models.CharField(max_length=300, blank=True, default="")
    ping_date = models.DateTimeField(null=True, blank=True)
    ping_note = models.CharField(max_length=300, blank=True, default="")

    def __str__(self):
        return self.name


class Occasion(SyncedModel):
    name = models.CharField(max_length=120)
    date = models.DateTimeField()
    tag = models.CharField(max_length=40)
    country = models.CharField(max_length=20, blank=True, default="")
    # Phase 3 (design doc): the greeting moves onto the occasion row. An
    # occasion tagged creatively (Thanksgiving under the New Year audience)
    # must not inherit the tag festival's template; empty = use the template.
    greeting = models.TextField(blank=True, default="")

    class Meta:
        ordering = ["date"]

    def __str__(self):
        return f"{self.name} {self.date:%Y-%m-%d}"


class OccasionTag(SyncedModel):
    """The user's tag vocabulary. Was a hardcoded nine-value enum in the
    client, which made the app unusable outside ID/MY/CN: no chip means no way
    to tag, and no tag means the festival never fires.

    ⚠ slug is the join key, carried as a plain string by Person.occasion_tags,
    Occasion.tag and Money.occasion_tag. The built-ins keep the old enum names
    as slugs, so nothing already stored had to migrate."""

    slug = models.CharField(max_length=40)
    label = models.CharField(max_length=120)
    hint = models.CharField(max_length=120, blank=True, default="")
    greeting = models.TextField(blank=True, default="")
    sort_order = models.IntegerField(default=0)
    built_in = models.BooleanField(default=False)

    class Meta(SyncedModel.Meta):
        ordering = ["sort_order", "label"]

    def __str__(self):
        return self.label


class Engagement(SyncedModel):
    name = models.CharField(max_length=200)
    # ⚠ Not a pipeline. Ralali is a jv, not a deal.
    type = models.CharField(max_length=20, default="deal")
    counterparty_id = models.CharField(max_length=36, blank=True, default='')
    # ⚠ FREE TEXT ON PURPOSE. A dropdown of stages makes this a sales tool.
    status = models.CharField(max_length=200, blank=True, default="")
    value_minor = models.BigIntegerField(null=True, blank=True)
    currency = models.CharField(max_length=8, blank=True, default="")
    notes = models.TextField(blank=True, default="")

    def __str__(self):
        return self.name


class Money(SyncedModel):
    date = models.DateTimeField()
    direction = models.CharField(max_length=4)  # in | out
    amount_minor = models.BigIntegerField()     # integer minor units, never float
    currency = models.CharField(max_length=8, default="CNY")
    label = models.CharField(max_length=200)
    status = models.CharField(max_length=10, default="expected")
    engagement_id = models.CharField(max_length=36, blank=True, default='')
    person_id = models.CharField(max_length=36, blank=True, default='')
    occasion_tag = models.CharField(max_length=40, blank=True, default="")

    class Meta:
        verbose_name_plural = "money"

    def __str__(self):
        return f"{self.label} {self.amount_minor}"


class Note(SyncedModel):
    date = models.DateTimeField()
    text = models.TextField(blank=True, default="")
    person_id = models.CharField(max_length=36, blank=True, default='')
    engagement_id = models.CharField(max_length=36, blank=True, default='')
    tag = models.CharField(max_length=40, blank=True, default="")


class Touch(SyncedModel):
    person_id = models.CharField(max_length=36)
    date = models.DateTimeField()
    one_line = models.CharField(max_length=300, blank=True, default="")


class Meeting(SyncedModel):
    """⚠ The only synced row with a TIME rather than just a date. Occasions are
    whole days and touches record what already happened; a meeting is a
    commitment at 3pm, so starts_at carries the clock."""

    person_id = models.CharField(max_length=36, blank=True, default="")
    engagement_id = models.CharField(max_length=36, blank=True, default="")
    title = models.CharField(max_length=200)
    starts_at = models.DateTimeField()
    duration_minutes = models.IntegerField(default=60)
    location = models.CharField(max_length=200, blank=True, default="")
    notes = models.TextField(blank=True, default="")

    def __str__(self):
        return f"{self.title} @ {self.starts_at:%Y-%m-%d %H:%M}"


class Task(SyncedModel):
    """A to-do. ⚠ due_date is a DAY, not a time, and done_at is a timestamp
    rather than a bool — when it was ticked off is worth keeping."""

    title = models.CharField(max_length=300)
    notes = models.TextField(blank=True, default="")
    # Client-set, unlike updated_at: it orders an undated checklist, and the
    # moment the row was written on the device is the moment that matters.
    created_at = models.DateTimeField(null=True, blank=True)
    due_date = models.DateTimeField(null=True, blank=True)
    done_at = models.DateTimeField(null=True, blank=True)
    person_id = models.CharField(max_length=36, blank=True, default="")
    engagement_id = models.CharField(max_length=36, blank=True, default="")

    def __str__(self):
        return self.title


class AuthToken(models.Model):
    """A bearer token belonging to one account and one device.

    ⚠ Only the HASH is stored — see core.auth.hash_token. A leaked database or
    an scp'd backup then contains no usable credential.

    One row per device rather than one per account, so signing out the phone
    leaves the Mac signed in, and a lost phone can be cut off on its own."""

    key_hash = models.CharField(max_length=64, unique=True, db_index=True)
    user = models.ForeignKey(
        "auth.User", on_delete=models.CASCADE, related_name="tokens"
    )
    label = models.CharField(max_length=64, blank=True, default="")
    created_at = models.DateTimeField(auto_now_add=True)
    last_used_at = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return f"{self.user.username} / {self.label or 'unnamed device'}"
